[toolchain]
anchor_version = "0.32.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
chronovault = "EzHNPN4VCbZZzBTk8S24vbzhtxFkMHEvSNmJCD8GqEcy"

[programs.devnet]
chronovault = "EzHNPN4VCbZZzBTk8S24vbzhtxFkMHEvSNmJCD8GqEcy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/*"]
